server:
  port: 8880
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  timeout: 30 # Seconds
  
database:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  dbname: todo-api-db
  sslmode: disable
  schema: public

secretkey:
  jwtsecret: cVU(xdc%xnZ6B2#Euutn3+Lg7PY#rFv^g(f(VdGh!YNe&WzpRfmhxmY6#Cg%

langs:
  - "en" # default
  - "th"
  - "fr"